<a href="https://colab.research.google.com/github/madhavadama/tensorflow/blob/master/Boston_Housing_Prices_Normalized.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Building a Linear Regression Model

In [0]:
import tensorflow as tf
import numpy as np

Reset Default graph - Needed only for Jupyter notebook

In [0]:
tf.reset_default_graph()

# Step 1 - Collect Data

In [0]:
#Good people at tensorflow have provided the data 
from tensorflow.contrib.learn import datasets

boston = datasets.load_dataset('boston')

Instructions for updating:
Please use tf.data.
Instructions for updating:
Use scikits.learn.datasets.
Instructions for updating:
Use tf.data instead.


In [0]:
boston.data[1:10]

array([[2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9690e+02, 9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        7.1850e+00, 6.1100e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9283e+02, 4.0300e+00],
       [3.2370e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        6.9980e+00, 4.5800e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9463e+02, 2.9400e+00],
       [6.9050e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        7.1470e+00, 5.4200e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9690e+02, 5.3300e+00],
       [2.9850e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        6.4300e+00, 5.8700e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9412e+02, 5.2100e+00],
       [8.8290e-02, 1.2500e+01, 7.8700e+00, 0.0000e+00, 5.2400e-01,
        6.0120e+00, 6.6600e

In [0]:
boston.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [0]:
boston.target.shape

(506,)

#Step 1a - Features and Target

In [0]:
#Input features
features = np.array(boston.data)

#Actual output
prices = np.array(boston.target)
prices = np.reshape(prices,[-1,1])


In [0]:
features

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [0]:
prices

array([[24. ],
       [21.6],
       [34.7],
       [33.4],
       [36.2],
       [28.7],
       [22.9],
       [27.1],
       [16.5],
       [18.9],
       [15. ],
       [18.9],
       [21.7],
       [20.4],
       [18.2],
       [19.9],
       [23.1],
       [17.5],
       [20.2],
       [18.2],
       [13.6],
       [19.6],
       [15.2],
       [14.5],
       [15.6],
       [13.9],
       [16.6],
       [14.8],
       [18.4],
       [21. ],
       [12.7],
       [14.5],
       [13.2],
       [13.1],
       [13.5],
       [18.9],
       [20. ],
       [21. ],
       [24.7],
       [30.8],
       [34.9],
       [26.6],
       [25.3],
       [24.7],
       [21.2],
       [19.3],
       [20. ],
       [16.6],
       [14.4],
       [19.4],
       [19.7],
       [20.5],
       [25. ],
       [23.4],
       [18.9],
       [35.4],
       [24.7],
       [31.6],
       [23.3],
       [19.6],
       [18.7],
       [16. ],
       [22.2],
       [25. ],
       [33. ],
       [23.5],
       [19

In [0]:
prices.shape

(506, 1)

How many examples do we have?

# Building the graph

Define input data placeholders

In [0]:
#Input features
x = tf.placeholder(shape=[None,13],dtype=tf.float32, name='x-input')

#Actual Output
# Actual Y Value 
y_ = tf.placeholder(shape=[None,1],dtype=tf.float32, name='y-input')

In [0]:
x

<tf.Tensor 'x-input:0' shape=(?, 13) dtype=float32>

In [0]:
y_

<tf.Tensor 'y-input:0' shape=(?, 1) dtype=float32>

Normalize Data

In [0]:
x_n = tf.nn.l2_normalize(x,1)

In [0]:
x_n

<tf.Tensor 'l2_normalize:0' shape=(?, 13) dtype=float32>

Define Weights and Bias

In [0]:
W = tf.Variable(tf.zeros(shape=[13,1]), name="Weights")
b = tf.Variable(tf.zeros(shape=[1]),name="Bias")

<tf.Variable 'Weights:0' shape=(13, 1) dtype=float32_ref>

Prediction - make sure to use normalized input features

In [0]:
#Matrix, Metrices, Tensors 

In [0]:
# Predition 
y = tf.add(tf.matmul(x_n,W),b,name='output')
# y = w1x1 + w2x2 + w3x3 + ......... + w13x13

Loss (Cost) Function

In [0]:
y

<tf.Tensor 'output:0' shape=(?, 1) dtype=float32>

In [0]:
loss = tf.reduce_mean(tf.square(y-y_),name='Loss')

# <Summation & mean (((P-A)^2 ))

GradientDescent Optimizer to minimize Loss

In [0]:
# defining the model through which the loss will be optimized 
train_op = tf.train.GradientDescentOptimizer(0.5).minimize(loss)

# model =  sklearn.LinearRegression(c=01).fit(x,y)
# model.predict(x)
# model.score(model.predict(x),y)

How do I define Learning Rate?

# Executing the Graph

In [0]:
#Lets start graph Execution
with tf.Session() as sess:
    # variables need to be initialized before we can use them
    # now is when the actual loading of variables will happen ---> lazy Loading 
    sess.run(tf.global_variables_initializer())
    
    #how many times data need to be shown to model
    training_epochs = 5000  
    
    for epoch in range(training_epochs):
        
        #Calculate train_op and loss
        # this is where you loss calculation and optimization will start happening 
        train_model, train_loss = sess.run([train_op,loss],feed_dict={x:features, y_:prices})
        
        if epoch % 100 == 0:
            print ('Training loss at step: ', epoch, ' is ', train_loss)
            print (sess.run([W,b]))
            # put loss, W, b in Dictionary 

Training loss at step:  0  is  592.1469
[array([[7.2091222e-02],
       [6.7363274e-01],
       [3.8339737e-01],
       [3.6395458e-03],
       [2.2200951e-02],
       [2.7616996e-01],
       [2.6348557e+00],
       [1.7608342e-01],
       [3.0071834e-01],
       [1.4883699e+01],
       [7.5592577e-01],
       [1.5748421e+01],
       [4.2662460e-01]], dtype=float32), array([22.532808], dtype=float32)]
Training loss at step:  100  is  62.029507
[array([[-1.3966086e+00],
       [ 9.4867220e+00],
       [-1.7653874e+00],
       [ 6.2991865e-02],
       [ 4.1523003e-03],
       [ 1.0707603e+00],
       [-3.5260797e+00],
       [ 2.1609995e-01],
       [ 6.4603068e-02],
       [-3.3688614e+00],
       [-3.5347813e-01],
       [ 1.8489540e+01],
       [-5.0690641e+00]], dtype=float32), array([13.04741], dtype=float32)]
Training loss at step:  200  is  60.355377
[array([[-2.39483142e+00],
       [ 1.57501020e+01],
       [-3.15798903e+00],
       [ 1.23543814e-01],
       [ 1.09389634e-03],
 

In [0]:
#Summary is a TensorFlow op that creates protocol buffers containing summarized data


training_loss = tf.summary.scalar('train_loss',loss)


In [0]:
training_loss

<tf.Tensor 'train_loss:0' shape=() dtype=string>

In [0]:
log_dir = "/content/log/"

In [0]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    training_epochs = 1000
    #Logging and Saving graph
    saver = tf.train.Saver()
    writer = tf.summary.FileWriter(log_dir, graph=tf.get_default_graph())
    #a python class that writes data to disk for Tensorboard
    for epoch in range(training_epochs):
        train_model, train_loss, loss_log = sess.run([train_op,loss,training_loss],feed_dict={x:features, y_:prices})
        writer.add_summary(loss_log, epoch)
        if epoch % 100 == 0:
            print ('Training loss at step: ', epoch, 'is', train_loss)
            print ('Log loss at step:', epoch, 'is', loss_log)
    saver.save(sess,log_dir + '/' + 'boston.ckpt')
        

Training loss at step:  0 is 592.1469
Log loss at step: 0 is b'\n\x11\n\ntrain_loss\x15g\t\x14D'
Training loss at step:  100 is 62.92511
Log loss at step: 100 is b'\n\x11\n\ntrain_loss\x15P\xb3{B'
Training loss at step:  200 is 61.639965
Log loss at step: 200 is b'\n\x11\n\ntrain_loss\x15S\x8fvB'
Training loss at step:  300 is 60.64175
Log loss at step: 300 is b"\n\x11\n\ntrain_loss\x15'\x91rB"
Training loss at step:  400 is 59.841866
Log loss at step: 400 is b'\n\x11\n\ntrain_loss\x15\x12^oB'
Training loss at step:  500 is 59.183144
Log loss at step: 500 is b'\n\x11\n\ntrain_loss\x15\x8a\xbblB'
Training loss at step:  600 is 58.625896
Log loss at step: 600 is b'\n\x11\n\ntrain_loss\x15\xeb\x80jB'
Training loss at step:  700 is 58.142456
Log loss at step: 700 is b'\n\x11\n\ntrain_loss\x15\xe0\x91hB'
Training loss at step:  800 is 57.713425
Log loss at step: 800 is b'\n\x11\n\ntrain_loss\x15\x8c\xdafB'
Training loss at step:  900 is 57.3251
Log loss at step: 900 is b'\n\x11\n\ntrain_los